import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Title from "@/components/title";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import Signal from "@/components/Head/Signal";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="flex flex-col items-center justify-center h-screen bg-[url('/img/bg2.jpg')] bg-cover ">
        <Theme>
          <section className="shadow-2xl p-6 rounded-2xl backdrop-blur-sm bg-white/50">
            <Signal />
            <Title />
            {children}
          </section>
        </Theme>
      </body>
    </html>
  );
}
